### ISSUE TITLE
Combo calculator allows combos that contain feature dependencies.

### ISSUE THREAD

**Issue by nihohit** [TheBevyFlock/flag-frenzy#19]
```
[dependencies]
foo = []
bar = ["foo"]
foobar = ["bar"]
```

The combos ["foobar", "bar"], ["foobar", "foo"] & ["bar", "foo"] should be omitted, since they're implied by the dependency graph. They should be automatically treated as 
```
[[rule]]
when = "foobar"
require = ["foo", "bar"]
[[rule]]
when = "foo"
require = ["bar"]
```

**Comment by BD103** [comment]
I agree. Feature dependencies are currently ignored, but it's leading to edge cases like these. Thanks for the report!

**Comment by nihohit** [comment]
I'm willing to try and contribute a fix, just wanted to make sure - are you
allocation-shy, or is it ok to build a dependency tree with lots of cloned
strings?

**Comment by BD103** [comment]
All feature names are interned in [this module](https://github.com/TheBevyFlock/flag-frenzy/blob/main/src/intern.rs). If you need help with the code, I'm `@BD103` on Bevy's Discord! :)
